version: "3.7"
services:

  db:
    build: 
      context: ./db
      args:
        - DB_SCHEMA=e2.12.0.sql
    image: eramba_db-enterprise:local
    container_name: Eramba_mariadb
    env_file:
      - eramba_vars.env
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - eramba_db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      eramba_net:
    restart: always

  web:
    build: 
      context: ./eramba
      args:
        - HTTPD_USER=www-data
    image: eramba_web-enterprise:local
    env_file:
      - eramba_vars.env
    container_name: Eramba_httpd
    volumes: 
      - ./eramba/certs:/certs
      - ./eramba/database.php:/var/www/html/app/Config/database.php
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - db
    networks:
      eramba_net:
    restart: always

volumes:
  eramba_db:

networks:
  eramba_net:
    name: Eramba_Net
